### ISSUE TITLE
Selection is not cleared in other buffers when current buffer is killed

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [alvarogonzalezsotillo/region-occurrences-highlighter#12]
**How to reproduce**
1. Activate `region-occurrences-highlighter-all-visible-buffers`
2. Open two buffers, A and B
3. Select some text in buffer A that highlights some text in buffer B
4. Kill buffer A without deselecting text
5. The text remains highlighted in buffer B

**Expected behaviour**
- The text iin buffer B should be unhighlighted after the buffer A is closed.

**Workarround**

- Use `hi-lock-unface-buffer` in every buffer with the highlighted text

**Comment by alvarogonzalezsotillo** [comment]
Maybe add a hook to `kill-buffer-hook`

```lisp
(region-occurrences-highlighter--kill-buffer-hook()
   "Deactivate the mark before killing the buffer."
  (deactivate-mark))

;; in region-occurrences-highlighter--enable
(add-hook 'kill-buffer-hook #'my-deactivate-mark-before-kill)

;; in region-occurrences-highlighter--disable
(remove-hook 'kill-buffer-hook #'my-deactivate-mark-before-kill)
```

**Comment by jcs090218** [comment]
I can reproduce this. 🤔 Maybe use `window-buffer-change-functions` instead of `kill-buffer-hook` since the highlighting remains even when the buffer is changed.

**Comment by alvarogonzalezsotillo** [comment]
I found no issues calling `region-occurrences-highlighter--change-hook` after deactivate the region. My code is in pull request #13 

```lisp
(defun region-occurrences-highlighter--kill-buffer-hook()
  "Deactivate the mark before killing the buffer."
  (deactivate-mark)
  (region-occurrences-highlighter--change-hook))
```

**Comment by jcs090218** [comment]
It seems like it also happens after switching buffers (including killing buffers). The `window-buffer-change-functions` hook should cover most of this scenario. WDYT?

**Comment by alvarogonzalezsotillo** [comment]
For me, the ability to have selected text in more than one buffer, and highlight all the different texts, is the desired behaviour.

Maybe this can be controlled by a customizable variable like `region-occurrences-hightlighter-use-all-regions`.

Maybe each selection from each buffer have to use a different highlight colour, but I don't know how to implement this.

**Comment by jcs090218** [comment]
Got it! I personally don't use `region-occurrences-highlighter-all-visible-buffers`, so I don't have a strong opinion on it. 🤔
