### ISSUE TITLE
Don't select whitespaces and tabs?

### ISSUE THREAD

**Issue by jcs090218** [alvarogonzalezsotillo/region-occurrences-highlighter#4]
What do you think about this? Maybe just make a new flag variable for backward compatibility?

**Comment by alvarogonzalezsotillo** [comment]
It seems a good idea to disable highlighting when the selection contains whitespaces only.
I will work on it after the summer.

**Comment by jcs090218** [comment]
@alvarogonzalezsotillo Don't forget the tabs too! :)

**Comment by alvarogonzalezsotillo** [comment]
I have added a regexp option that ignores selections containing only blanks (including tabs) and newlines.

can you check the code on the ignore-whitespace branch?

I will merge it into master branch after some testing (im currently using emacs in termux, so im not very confident about it )


https://github.com/alvarogonzalezsotillo/region-occurrences-highlighter/blob/ignore-whitespace/readme.org

**Comment by jcs090218** [comment]
I have tested and it works great with both spaces, tabs and newlines! :D Good work! Anyway, you might want to bump the version after this update!
